/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.gradle.testfixtures.ProjectBuilder
import spock.lang.Specification

/**
 * A simple unit test for the 'org.example.greeting' plugin.
 */
class XqPluginsPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        println "Applying plugin to project"

        then:
        true == true
    }
}
